/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MFrame.java
 *
 * Created on Mar 2, 2011, 9:16:36 AM
 */
package ru.panov.andy;

import ru.panov.help.HelpFrame;

import java.awt.*;

/**
 * @author aware
 */
public class MFrame extends javax.swing.JFrame {

    OberbekWheel wheel = new OberbekWheel();
    OberekWheelView view = new OberekWheelView(wheel);

    /**
     * Creates new form MFrame
     */
    public MFrame() {
        initComponents();
        experimentPane.setLayout(new BorderLayout());
        experimentPane.add(view, BorderLayout.CENTER);

        new Thread(new Timer(timeLabel)).start();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(500, (int) dim.getHeight() - 100);
        this.setLocationRelativeTo(null);
    }

    public void setSlidersEnabled(boolean param) {
        sliderCountDopCargo.setEnabled(param);
        sliderMDopCargo.setEnabled(param);
        sliderMcarg.setEnabled(param);
        sliderRval.setEnabled(param);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        sliderMcarg = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sliderRval = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sliderCountDopCargo = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        experimentPane = new javax.swing.JPanel();
        buttonStart = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        buttonStop = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        buttonReset = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        startLabel = new javax.swing.JLabel();
        stopLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        sliderMDopCargo = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Маятник Обербека");
        setMinimumSize(new java.awt.Dimension(750, 550));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Масса груза на нити, грамм"));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new java.awt.BorderLayout());

        sliderMcarg.setMaximum(1000);
        sliderMcarg.setMinimum(100);
        sliderMcarg.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMcargStateChanged(evt);
            }
        });
        jPanel1.add(sliderMcarg, java.awt.BorderLayout.CENTER);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sliderMcarg, org.jdesktop.beansbinding.ELProperty.create("  ${value}, гр."), jLabel1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Радиус шкива, мм"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        sliderRval.setMaximum(200);
        sliderRval.setMinimum(3);
        sliderRval.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRvalStateChanged(evt);
            }
        });
        jPanel2.add(sliderRval, java.awt.BorderLayout.CENTER);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sliderRval, org.jdesktop.beansbinding.ELProperty.create("  ${value}, мм."), jLabel2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel2.add(jLabel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Количество грузов"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        sliderCountDopCargo.setMaximum(4);
        sliderCountDopCargo.setMinorTickSpacing(2);
        sliderCountDopCargo.setPaintLabels(true);
        sliderCountDopCargo.setPaintTicks(true);
        sliderCountDopCargo.setSnapToTicks(true);
        sliderCountDopCargo.setValue(0);
        sliderCountDopCargo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderCountDopCargoStateChanged(evt);
            }
        });
        jPanel3.add(sliderCountDopCargo, java.awt.BorderLayout.CENTER);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sliderCountDopCargo, org.jdesktop.beansbinding.ELProperty.create("  ${value}, шт."), jLabel3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel3.add(jLabel3, java.awt.BorderLayout.LINE_END);

        experimentPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        experimentPane.setMinimumSize(new java.awt.Dimension(300, 400));
        experimentPane.setPreferredSize(new java.awt.Dimension(300, 400));

        javax.swing.GroupLayout experimentPaneLayout = new javax.swing.GroupLayout(experimentPane);
        experimentPane.setLayout(experimentPaneLayout);
        experimentPaneLayout.setHorizontalGroup(
            experimentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );
        experimentPaneLayout.setVerticalGroup(
            experimentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        buttonStart.setText("Старт");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        timeLabel.setFont(new java.awt.Font("Ubuntu", 0, 24));
        timeLabel.setText("jLabel1");

        buttonStop.setText("Стоп");
        buttonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopActionPerformed(evt);
            }
        });

        buttonReset.setText("Сброс");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24));
        jLabel4.setText("Старт:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24));
        jLabel5.setText("Стоп:");

        startLabel.setFont(new java.awt.Font("Ubuntu", 0, 24));

        stopLabel.setFont(new java.awt.Font("Ubuntu", 0, 24));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stopLabel)
                    .addComponent(startLabel))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(startLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(stopLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Масса одного доп. груза, гр."));
        jPanel5.setLayout(new java.awt.BorderLayout());

        sliderMDopCargo.setMaximum(1000);
        sliderMDopCargo.setMinimum(100);
        sliderMDopCargo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMDopCargoStateChanged(evt);
            }
        });
        jPanel5.add(sliderMDopCargo, java.awt.BorderLayout.CENTER);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sliderMDopCargo, org.jdesktop.beansbinding.ELProperty.create("  ${value}, гр."), jLabel6, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel5.add(jLabel6, java.awt.BorderLayout.LINE_END);

        jMenu1.setText("Справка");

        jMenuItem1.setText("Порядок выполнения...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(timeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(experimentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(buttonStop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(experimentPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(buttonStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonStop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonReset))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(timeLabel)))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        new Thread(view).start();
        startLabel.setText(timeLabel.getText());
        stopLabel.setText("");

        setSlidersEnabled(false);

    }//GEN-LAST:event_buttonStartActionPerformed

    private void buttonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopActionPerformed
        if (view.isInprogress()) {
            stopLabel.setText(timeLabel.getText());
            view.setInprogress(false);
        }
        setSlidersEnabled(true);
    }//GEN-LAST:event_buttonStopActionPerformed

    private void sliderCountDopCargoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderCountDopCargoStateChanged
        wheel.setDopcargoCount(sliderCountDopCargo.getValue());
        view.initWheel(); //перерисовываем маятник
        buttonResetActionPerformed(null);
    }//GEN-LAST:event_sliderCountDopCargoStateChanged

    private void sliderMDopCargoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMDopCargoStateChanged
        wheel.setDopcargoMassa(sliderMDopCargo.getValue() / 1000.0d);
        buttonResetActionPerformed(null);
    }//GEN-LAST:event_sliderMDopCargoStateChanged

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        setSlidersEnabled(true);
        startLabel.setText("");
        stopLabel.setText("");
        view.resetState();
        experimentPane.repaint();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void sliderMcargStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMcargStateChanged
        wheel.setCargoMassa(sliderMcarg.getValue() / 1000.0d);
        buttonResetActionPerformed(null);
    }//GEN-LAST:event_sliderMcargStateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        HelpFrame help = new HelpFrame();
        help.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void sliderRvalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRvalStateChanged
        wheel.setValRadius(sliderRval.getValue() / 1000.0d);
    }//GEN-LAST:event_sliderRvalStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonStart;
    private javax.swing.JButton buttonStop;
    private javax.swing.JPanel experimentPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider sliderCountDopCargo;
    private javax.swing.JSlider sliderMDopCargo;
    private javax.swing.JSlider sliderMcarg;
    private javax.swing.JSlider sliderRval;
    private javax.swing.JLabel startLabel;
    private javax.swing.JLabel stopLabel;
    private javax.swing.JLabel timeLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
